/* Project photo data — shared by Design C. Generated from assets/projects/. */
var TW_PROJECTS = {
  stallion: { name: "The Stallion House", place: "Portland, OR", photos: ["StallionHouse__001_websize.jpg", "StallionHouse__007_websize.jpg", "StallionHouse__013_websize.jpg", "StallionHouse__014_websize.jpg", "StallionHouse__028_websize.jpg", "StallionHouse__033_websize.jpg", "StallionHouse__035_websize.jpg", "StallionHouse__037_websize.jpg", "StallionHouse__038_websize.jpg", "StallionHouse__043_websize.jpg", "StallionHouse__050_websize.jpg", "StallionHouse__053_websize.jpg"] },
  bristol: { name: "The Bristol House", place: "Portland, OR", photos: ["BristolHouse_04_websize.jpg", "BristolHouse_07_websize.jpg", "BristolHouse_08_websize.jpg", "BristolHouse_14_websize.jpg", "BristolHouse_18_websize.jpg", "BristolHouse_28_websize.jpg", "BristolHouse_30_websize.jpg", "BristolHouse_53_websize.jpg", "BristolHouse_58_websize.jpg", "Bristol_6801_websize.jpg"] },
  spinosa: { name: "The Spinosa House", place: "Portland, OR", photos: ["Spinosa_6479_websize.jpg", "Spinosa_6492_websize.jpg", "Spinosa_6501_websize.jpg", "Spinosa_6515_websize.jpg", "Spinosa_6533_websize.jpg", "Spinosa_6537_websize.jpg", "Spinosa_6546_websize.jpg", "Spinosa_6562_websize.jpg", "Spinosa_6579_websize.jpg", "Spinosa_6586_websize.jpg", "Spinosa_6632_websize.jpg", "Spinosa_6654_websize.jpg", "Spinosa_6657_websize.jpg"] },
  alfred: { name: "The Alfred House", place: "Portland, OR", photos: ["alfred1_websize.jpg", "alfred2_websize.jpg", "AlfredHouse_20_websize.jpg", "AlfredHouse_31_websize.jpg", "AlfredHouse_43_websize.jpg", "AlfredHouse_44_websize.jpg", "AlfredHouse_45_websize.jpg", "AlfredHouse_49_websize.jpg", "AlfredHouse_71_websize.jpg"] },
  waxwing: { name: "The Waxwing House", place: "Portland, OR", photos: ["WaxwingHouse_34_websize.jpg", "WaxwingHouse_39_websize.jpg", "WaxwingHouse_41_websize.jpg", "WaxwingHouse_47_websize.jpg", "WaxwingHouse_52_websize.jpg", "WaxwingHouse_59_websize.jpg"] },
  weir: { name: "The Weir House", place: "Portland, OR", photos: ["WeirHouse_10_websize.jpg", "WeirHouse_17_websize.jpg", "WeirHouse_33_websize.jpg", "WeirHouse_40_websize.jpg", "WeirHouse_52_websize.jpg"] }
};
